appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
matrix:
- []
- - [VC_VERSION, 14]
  - [CONDA_PY, 36]
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gx/BH2ni0VhxRZ5vUOdF6ggm4W+kSGzRJlExZLmuW3IkKCbUyJ0TESeuUdfCXG85pvA0Y/ZLm8bArYqNoe761Tk/m7E9rfUnQuleuPt6E0UBQxH4CU4rgAfzcLCYONGd2OpSWtjpivKKy2AeehWnGeMv6TdiujScCI/ZcMkZYcv2z9XBmtrsZV96Omhu4XhguRHWG/42+h/dLDfFCHz0GX52LlVsjuRRwK2xvH1eSIc6gMe/mRIH6X7NtMpqGa6Re6IPbm4fZbIOsFXBz+1Egj7wi+q6GeBoCkyuySb2KEHuYOt/WRsn8J3dvPACuWECZLoML6MNcrhIjMG2QZb0+1QTAXAAvVY2gbQt1G6lHeVS/LLiCt4xljWilt6ght0qTFGW/OJrbdtBHWE0NxvYxQcuR2Zssun4+rLzabfnrstAvuSNrCMJftAoXJ5cScTBWfD6Vzy1s3BL+VOZvA8K2kPHCJilV5uWlYtqAsnXmgYNuf3T4VQXh85BDjM/M7imBgpEOWOMyMm2fhc9US9nIQdDjKjEFiC+CCd/DNcuEYqkrlYYgvgFuDaxdzbDB9vCkN0YEeGirbOExVtMXcc4fiIObN6BqO98MLqZAAV6e+QUW2h5M2S+WrI+WUXJRptN5dkO0eu4At+G5vcM8bOfI/PrM6/zqv3+h/t0QlXCIzE=}
